language: java
sudo: false
notifications:
  hipchat:
    rooms:
      secure: leA9IWGmnGTH6B3h2FKJKY/8Cw8M6aIhwUulzS9CFOV3ux4MCBjKYqIRDPbilYXMIVVTREQsmRtDjIqcqtLmTIUOmzd7sjH20exaeFNJDV8BM126fIq1LhywZUpCc1/ZG2P3HBOgRKQCY6hujL+eNaMbGTYfjBgym/V+bROhfCg=
deploy:
  provider: releases
  api_key:
    secure: alaeOarV4869kZfE9zAqdARLndMWickS00K1OxT+C94db+Ko0oyIF3XVJD+u4r34xCvmlpiBdkom5C5UyI1z5CptwkONdH9kubHdTYey3Wpw0l7OQbpha0PXfUzj9V2bJqySgxx4yt3PJs49g9nOjWKuSn57c2AZ3ziAeKYZvQk=
  file: build/libs/xld-docker-plugin-2.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-docker-plugin
